# Generated by Django 5.0.4 on 2024-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
    ]
